NEDS-71-72-75
nordic-institute/harmony-common pull request #6
Opened 2022-01-09 06:51 UTC by petkivim

- Create TLS truststore during installation [NEDS-71 ](https://jira.niis.org/browse/NEDS-71)
  - Create TLS truststore automatically during installation.
  - Import the public certificate of the private TLS key to the TLS truststore.
  - Fix errors in keytool commands in the Static Discovery Configuration Guide.
  - Fix incorrect DB username in the postinstall script.
  - Fix incorrect group name in the postinstall script.
  - Add the TLS truststore configuration in the Tomcat default configuration.
- Create One-Way SSL configuration during installation [NEDS-72](https://jira.niis.org/browse/NEDS-72)
  - Create `/etc/harmony-ap/clientauthentication.xml` configuration file.
  - Set the TLS truststore password.
- Prompt Party Name during installation process [NEDS-75](https://jira.niis.org/browse/NEDS-75)
  - Prompt Party Name during installation process.
  - Use the given Party Name as sign and TLS key alias.
  - Update the alias in domibus.properties.
- Update AP installation guide.
- Update static discovery configuration guide.

2022-01-10 12:23 UTC, raits requested changes

2022-01-11 05:02 UTC, petkivim commented on doc/harmony-ap_installation_guide.md
> +- configures One-Way SSL between two Access Points;
Good point. I updated the wording and added a note about sharing and importing certificates manually.

2022-01-11 07:23 UTC, raits approved these changes

2022-01-11 07:23 UTC, raits commented
Looks good to me

2022-01-11 07:26 UTC, merged