NEDS-172: Remove hardcoded jvm paths
nordic-institute/harmony-common pull request #67
Opened 2024-01-10 11:47 UTC by diegomartinn

2024-01-10 13:21 UTC, petkivim requested changes
Everything else looks good, but the branch should be merged into `develop` branch and not into `main`. Feature branches are merged into `develop` and `develop` is merged into `main` after releases.

2024-01-11 10:39 UTC, petkivim approved these changes

2024-01-11 10:58 UTC, petkivim commented
The documentation should be updated too:

https://github.com/nordic-institute/harmony-common/blob/main/doc/harmony-ap_installation_guide.md#21-prerequisites-to-installation

2024-01-11 13:41 UTC, jhyoty commented
Rebased the branch on top of develop to keep history clean

2024-01-25 11:44 UTC, merged