NEDS-176: Add support for multiple message brokers to the docker image
nordic-institute/harmony-common pull request #71
Opened 2024-03-01 14:03 UTC by diegomartinn

2024-03-01 14:52 UTC, diegomartinn commented on packaging/ap/docker/entrypoint.sh
> +      set_prop_tmp "activeMQ.transportConnector.uri"   "failover:($(add_prefix_suffix "$ACTIVEMQ_BROKER_HOST" "tcp://" ":61616"))?randomize=false"
We used the static post as [domibus.properties](https://github.com/nordic-institute/harmony-access-point/blob/harmony-main/Tomcat/Domibus-MSH-tomcat/src/main/resources/config/domibus.properties#L91) doesn't give the option to change it. We can add a new configuration property in the docker image that defaults to `61616` if not set.

2024-03-01 14:52 UTC, diegomartinn commented on packaging/ap/docker/entrypoint.sh
> +      set_prop_tmp "activeMQ.JMXURL"                   "$(add_prefix_suffix "$ACTIVEMQ_BROKER_HOST" "service:jmx:rmi:///jndi/rmi://" ":1199/jmxrmi")"
Same solution than the previous comment

2024-03-02 05:47 UTC, petkivim commented on packaging/ap/docker/entrypoint.sh
> +      set_prop_tmp "activeMQ.transportConnector.uri"   "failover:($(add_prefix_suffix "$ACTIVEMQ_BROKER_HOST" "tcp://" ":61616"))?randomize=false"
I think it would be better make it configurable with the default value of `61616`.

2024-03-02 05:47 UTC, petkivim commented on packaging/ap/docker/entrypoint.sh
> +      set_prop_tmp "activeMQ.JMXURL"                   "$(add_prefix_suffix "$ACTIVEMQ_BROKER_HOST" "service:jmx:rmi:///jndi/rmi://" ":1199/jmxrmi")"
Also in this case, I think it would be better make it configurable with the default value of `1199`.

2024-03-04 15:42 UTC, petkivim requested changes
Please update the `harmony-ap_docker_installation_guide.md` version number and version history table. Otherwise the changes look good.

2024-03-05 10:11 UTC, diegomartinn commented
You are right, missed the changelog at the beginning of the document :)

2024-03-05 10:54 UTC, petkivim approved these changes
Looks good to me.

2024-03-05 10:58 UTC, merged